---
repos:
  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
      - id: black
        args: [--safe, --quiet, --target-version, py38]
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==21.12b0]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: requirements-txt-fixer
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: check-ast
      - id: detect-private-key
      - id: forbid-new-submodules
  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.16.0
    hooks:
      - id: validate_manifest
  - repo: https://github.com/PyCQA/isort
    rev: 5.5.0
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.920
    hooks:
      - id: mypy
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-docstrings"]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        exclude: ^\.github/workflows/*\.yml$
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
